#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

ScriptName = Test

1 = 1`%
2 = 5`%
3 = 100`%




Home:
Gui, Consol:Add, Edit, x5 y10 w335 h235 +ReadOnly +VScroll +HScroll vConsole gRead, 
Gui, Consol:Add, Button, x255 y280 w43 h23 gStart, Start
Gui, Consol:Add, Button, x300 y280 w43 h23, Stop
Gui, Consol:Show, w347 h308, %ScriptName% Console
return

ConsolGuiClose:
ExitApp
; This Gui is generated by X-GUI Creator




Start:
{
FileRead,Start,%A_WorkingDir%/Logs/starting.txt
FileRead,Loading,%A_WorkingDir%/Logs/loading.txt
FileRead,Completed,%A_WorkingDir%/Logs/Completed.txt
GuiControl,, Console, %Start%
}
sleep 300
gosub Start2
return


Start2:
Loop, read, %A_WorkingDir%/Logs/Log.txt
{
    Loop, parse, A_LoopReadLine, %A_Tab%
    {
		sleep 300
      GuiControl,, Console,%Loading% %A_LoopField%`%
    }
}
gosub Completed
return


Completed:
{
	GuiControl,, Console,%Completed%
}
return



esc::
ExitApp

Read:
	Loop, read, %A_WorkingDir%/Logs/Log.txt
	{
		last := console1
		FileRead, console1, %A_WorkingDir%\Logs\Log.txt
		if(console1 != last) {
			AddText(console1, HDConsole)
		}
	}
return



AddText(str, hwnd) {
    Static EM_SETSEL := 0x00B1, EM_REPLACESEL := 0x00C2
    SendMessage, EM_SETSEL, -2, -1, , ahk_id %hwnd%
    SendMessage, EM_REPLACESEL, True, &str, , ahk_id %hwnd%
}